### ISSUE TITLE
Occasional api test failure, "bad file descriptor, write"

### ISSUE THREAD

**Issue by mwcz** [spaship/spaship#224]
This happens intermittently on my machine, logging for future reference.

```
10:40:51 {nested-config} ~/projects/spaship/packages/api
$ npm test

> @spaship/api@0.5.0 test /home/mclayton/projects/spaship/packages/api
> ../../node_modules/.bin/jest --restoreMocks

 PASS  lib/db.apikey.test.js
  api.db.apikey
    attach
      ✓ should be able to attach to the collection (8ms)
    apikey CRUD
      ✓ should be able to create a new api key (8ms)
      ✓ should be able to get api keys by userid (6ms)
      ✓ should be able to get userid by apikey (7ms)
      ✓ should be able to delete a key (5ms)

 FAIL  lib/background/autosync.test.js
  api.autosync
    syncTarget
      lifecycle
        ✕ should start and stop (7ms)
        ✓ should sync targets while running (1ms)
        ✓ should sync targets periodically per target's timer
      disk cache
        ✓ should save to disk the response from a sync target (4ms)
        ✓ should save to disk the response from a sync target with subpaths (9ms)

  ● api.autosync › syncTarget › lifecycle › should start and stop

    EBADF: bad file descriptor, write



      at actualWrite (../common/node_modules/sonic-boom/index.js:272:24)
      at SonicBoom.Object.<anonymous>.SonicBoom.write (../common/node_modules/sonic-boom/index.js:154:5)
      at Object.write (../common/node_modules/pino/lib/tools.js:240:12)
      at Pino.write (../common/node_modules/pino/lib/proto.js:161:15)
      at Pino.LOG [as info] (../common/node_modules/pino/lib/tools.js:39:26)
      at Autosync.start (lib/background/autosync.js:1520:9)
      at Object.<anonymous> (lib/background/autosync.test.js:69:12)

 PASS  lib/metadata.test.js
  api.metadata
    write
      ✓ should add metadata to a deployed SPA (27ms)
    getAll
      ✓ should retrieve metadata for all deployed SPAs (6ms)
      ✓ should return an empty array if the webroot can't be accessed (1ms)
    get
      ✓ should retrieve metadata when given a spa's directory (1ms)

--------------------|----------|----------|----------|----------|-------------------|
File                |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
--------------------|----------|----------|----------|----------|-------------------|
All files           |     74.5 |    51.52 |    65.63 |    75.86 |                   |
 api                |    71.43 |       50 |     37.5 |    70.37 |                   |
  config.js         |    71.43 |       50 |     37.5 |    70.37 |... ,96,98,102,104 |
 api/lib            |    94.34 |    61.54 |      100 |    94.34 |                   |
  db.apikey.js      |      100 |    66.67 |      100 |      100 |                14 |
  db.js             |       75 |       50 |      100 |       75 |                10 |
  db.mock-mongo.js  |    88.89 |     62.5 |      100 |    88.89 |             12,22 |
  metadata.js       |      100 |      100 |      100 |      100 |                   |
 api/lib/background |    60.29 |    43.75 |    53.85 |    63.08 |                   |
  autosync.js       |    60.29 |    43.75 |    53.85 |    63.08 |... 11,112,131,141 |
--------------------|----------|----------|----------|----------|-------------------|
Test Suites: 1 failed, 2 passed, 3 total
Tests:       1 failed, 13 passed, 14 total
Snapshots:   0 total
Time:        1.466s, estimated 2s
Ran all test suites.
{"message":"ENOENT, no such file or directory '/fake/webroot'","code":"ENOENT","errno":-2,"path":"/fake/webroot"}
npm ERR! Test failed.  See above for more details.
```

**Comment by sayak-sarkar** [comment]
I can confirm that this happens for me as well. This is a valid issue.

**Comment by kunyan** [comment]
The issue is caused by this line
https://github.com/spaship/spaship/blob/e40036da877228f237aeec150b838bd7954a6379/packages/api/lib/background/autosync.js#L56

If we replace it to `log.debug()` or `log.trace()`. it wouldn't happen anymore

**Comment by mwcz** [comment]
Why?

**Comment by kunyan** [comment]
No idea, Actually, I also got another error. I think it might be related with my OS : mac OS

``` 
● api.autosync › syncTarget › disk cache › should save to disk the response from a sync target

    ENOENT, no such file or directory '/fake/webroot/spaship/test-target-1/index.html'

      91 |         });
      92 |         await as.syncTarget(target);
    > 93 |         const cache = await fsp.readFile("/fake/webroot/spaship/test-target-1/index.html");
         |                                 ^
      94 |         expect(cache.toString()).toEqual(responseText);
      95 |       });
      96 |
```



I think `mockfs` might has some issue with mac OS

**Comment by sayak-sarkar** [comment]
@kunyan I'm still getting this:

```
> @spaship/manager@0.7.0 test /Users/ssarkar/Work/spaship/packages/manager
> react-scripts test

lerna ERR! npm run test exited 1 in '@spaship/api'
lerna ERR! npm run test stdout:

> @spaship/api@0.7.0 test /Users/ssarkar/Work/spaship/packages/api
> ../../node_modules/.bin/jest --restoreMocks

[{"userid":"babyyoda","apikey":"fdf1fcb03dab8d28a97d2ab228225a196b9d99f0b3e1a2c1f6a05165ccb1d255","_id":"5e8574abcf06ce42f643fb8c"}]
--------------------|----------|----------|----------|----------|-------------------|
File                |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
--------------------|----------|----------|----------|----------|-------------------|
All files           |    76.25 |     52.5 |    68.57 |    77.42 |                   |
 api                |    71.43 |       50 |     37.5 |    70.37 |                   |
  config.js         |    71.43 |       50 |     37.5 |    70.37 |... 08,110,114,116 |
 api/lib            |    88.89 |    55.56 |    92.86 |    88.71 |                   |
  db.apikey.js      |    85.71 |       50 |    88.89 |    85.71 |          52,53,54 |
  db.js             |       75 |       50 |      100 |       75 |                10 |
  db.mongo-mock.js  |    88.89 |     62.5 |      100 |    88.89 |             12,22 |
  metadata.js       |       95 |      100 |      100 |    94.74 |                37 |
 api/lib/background |    66.67 |       50 |    61.54 |     69.7 |                   |
  autosync.js       |    66.67 |       50 |    61.54 |     69.7 |... 12,130,133,143 |
--------------------|----------|----------|----------|----------|-------------------|
{"message":"ENOENT, no such file or directory '/fake/webroot'","code":"ENOENT","errno":-2,"path":"/fake/webroot"}

lerna ERR! npm run test stderr:
PASS lib/db.apikey.test.js
  api.db.apikey
    attach
      ✓ should be able to attach to the collection (14ms)
    apikey CRUD
      ✓ should be able to create a new api key (59ms)
      ✓ should be able to get api keys by userid (6ms)
      ✓ should be able to get userid by apikey (3ms)
      ✓ should be able to get userid by hashedapikey (7ms)
      ✓ should be able to delete a key (8ms)

FAIL lib/background/autosync.test.js
  api.autosync
    syncTarget
      lifecycle
        ✓ should start and stop (8ms)
        ✓ should sync targets while running
        ✓ should sync targets periodically per target's timer
      disk cache
        ✕ should save to disk the response from a sync target (12ms)
        ✓ should save to disk the response from a sync target with subpaths (15ms)

  ● api.autosync › syncTarget › disk cache › should save to disk the response from a sync target

    Unhandled error. (Error {
      message: 'EBADF, bad file descriptor',
      code: 'EBADF',
      errno: -9
    })Error [ERR_UNHANDLED_ERROR]: Unhandled error. (Error {
      message: 'EBADF, bad file descriptor',
      code: 'EBADF',
      errno: -9
    })

      at SonicBoom.filterBrokenPipe (../common/node_modules/pino/lib/tools.js:287:12)
      at SonicBoom.release (../common/node_modules/pino/node_modules/sonic-boom/index.js:100:14)
      at wrapper (../../node_modules/mock-fs/lib/binding.js:858:7)
      at ../../node_modules/mock-fs/lib/binding.js:88:9

(node:82676) UnhandledPromiseRejectionWarning: Error: Caught error after test environment was torn down

ENOENT: no such file or directory, open '/fake/webroot/spaship/test-target-1/index.html'
(node:82676) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:82676) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Any idea what might be the issue here?
